package com.knust.campusserv.support.service;

import com.knust.campusserv.support.model.Review;
import com.knust.campusserv.support.repository.ReviewRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

@Service
public class ReviewService {

    @Autowired
    private ReviewRepository reviewRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Transactional
    public Review submitReview(String jobId, String reviewerId, String revieweeId, int rating, String comment, Review.ReviewDirection direction, boolean isAutoGenerated, String categoryId, java.util.List<String> tags) {
        // Reject if already exists
        if (reviewRepository.findByJobIdAndDirection(jobId, direction).isPresent()) {
            throw new IllegalArgumentException("Review already exists for this job in this direction.");
        }

        Review review = new Review();
        review.setId(UUID.randomUUID().toString());
        review.setJobId(jobId);
        review.setReviewerId(reviewerId);
        review.setRevieweeId(revieweeId);
        review.setRating(rating);
        review.setComment(comment);
        review.setDirection(direction);
        review.setIsAutoGenerated(isAutoGenerated);
        review.setCategoryId(categoryId);
        review.setTags(tags);
        
        review = reviewRepository.save(review);

        if (direction == Review.ReviewDirection.REQUESTER_TO_PROVIDER) {
            // Update provider_profiles natively in the same transaction
            String sql = "UPDATE provider_profiles SET " +
                         "total_reviews = total_reviews + 1, " +
                         "rating = COALESCE((SELECT AVG(rating) FROM reviews WHERE reviewee_id = ? AND direction = 'REQUESTER_TO_PROVIDER'), 0) " +
                         "WHERE id = ?";
            jdbcTemplate.update(sql, revieweeId, revieweeId);

            // Synchronize average rating to the users table
            String userSql = "UPDATE users SET " +
                             "rating = COALESCE((SELECT AVG(rating) FROM reviews WHERE reviewee_id = ? AND direction = 'REQUESTER_TO_PROVIDER'), 0) " +
                             "WHERE id = ?";
            jdbcTemplate.update(userSql, revieweeId, revieweeId);

            if (categoryId != null) {
                // UPSERT provider_category_ratings
                String catSql = "INSERT INTO provider_category_ratings (id, provider_id, category_id, review_count, rating) " +
                                "VALUES (?, ?, ?, 1, ?) " +
                                "ON CONFLICT (provider_id, category_id) DO UPDATE SET " +
                                "review_count = provider_category_ratings.review_count + 1, " +
                                "rating = COALESCE((SELECT AVG(rating) FROM reviews WHERE reviewee_id = ? AND category_id = ? AND direction = 'REQUESTER_TO_PROVIDER'), 0)";
                jdbcTemplate.update(catSql, UUID.randomUUID().toString(), revieweeId, categoryId, rating, revieweeId, categoryId);
            }
        }

        return review;
    }
}
