server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/campusserv
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1

paystack:
  secret-key: ${PAYSTACK_SECRET_KEY}
  webhook-secret: ${PAYSTACK_WEBHOOK_SECRET}
  callback-url: ${PAYSTACK_CALLBACK_URL:http://localhost:8080/payments/callback}

app:
  upload-dir: ${UPLOAD_DIR:../uploads/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: local-dev
  jpa:
    hibernate:
      ddl-auto: validate

paystack:
  secret-key: sk_test_mock_paystack_secret_key_ghana_knust
  webhook-secret: whsec_mock_paystack_webhook_verification_signature
  callback-url: http://localhost:8080/payments/callback
