-- V28__seed_verified_provider_accounts.sql
-- Creates two fully verified, approved provider accounts for testing.
--
-- Provider 1: Room Cleaning category
--   Email:    ama.asante@st.knust.edu.gh
--   Password: password
--
-- Provider 2: Tech Repair category
--   Email:    kwame.mensah@st.knust.edu.gh
--   Password: password
--
-- Both accounts:
--   - primary_role = PROVIDER (was approved directly, no secondary-role flow)
--   - account_status = ACTIVE
--   - is_verified = TRUE, verification_status = APPROVED
--   - Both wallets provisioned (student_wallets + provider_wallets)
--
-- BCrypt hash below is for the literal string "password" (cost factor 10).
-- Same hash used by all other test accounts in V7__create_supporting_table.sql.

-- ── 1. User rows ──────────────────────────────────────────────────────────────

INSERT INTO users (
    id,
    email,
    password_hash,
    full_name,
    role,
    is_verified,
    verification_status,
    is_provider,
    account_status,
    primary_role,
    primary_role_verified,
    secondary_role,
    secondary_role_status,
    secondary_role_acquired_at,
    active_role_view,
    service_category
) VALUES
-- Provider 1 — Room Cleaning
(
    'usr-provider-cleaning',
    'ama.asante@st.knust.edu.gh',
    '$2a$10$O.Y4uGv7lJbe5.6j27lJ7.fJ2eM8m9m5E8.e6X15tVvQ3WqK79oJu',
    'Ama Asante',
    'PROVIDER',
    TRUE,
    'APPROVED',
    TRUE,
    'ACTIVE',
    'PROVIDER',
    TRUE,
    NULL,
    NULL,
    NULL,
    'PROVIDER',
    'Room Cleaning'
),
-- Provider 2 — Tech Repair
(
    'usr-provider-techrepair',
    'kwame.mensah@st.knust.edu.gh',
    '$2a$10$O.Y4uGv7lJbe5.6j27lJ7.fJ2eM8m9m5E8.e6X15tVvQ3WqK79oJu',
    'Kwame Mensah',
    'PROVIDER',
    TRUE,
    'APPROVED',
    TRUE,
    'ACTIVE',
    'PROVIDER',
    TRUE,
    NULL,
    NULL,
    NULL,
    'PROVIDER',
    'Tech Repair'
);

-- ── 2. Provider profiles ──────────────────────────────────────────────────────

INSERT INTO provider_profiles (id, bio, rating, completed_jobs_count, approval_status)
VALUES
    (
        'usr-provider-cleaning',
        'Hostel and dorm room cleaning specialist. Reliable, thorough, and on time.',
        0.0,
        0,
        'VERIFIED'
    ),
    (
        'usr-provider-techrepair',
        'Laptop and mobile phone repairs. Software installs and hardware diagnostics.',
        0.0,
        0,
        'VERIFIED'
    );

-- ── 3. Student wallets (every user gets one regardless of role) ───────────────

INSERT INTO student_wallets (user_id, balance, held_balance, currency, version, created_at, updated_at)
VALUES
    ('usr-provider-cleaning',   0.00, 0.00, 'GHS', 0, NOW(), NOW()),
    ('usr-provider-techrepair', 0.00, 0.00, 'GHS', 0, NOW(), NOW());

-- ── 4. Provider wallets ───────────────────────────────────────────────────────

INSERT INTO provider_wallets (user_id, balance, currency, version, created_at, updated_at)
VALUES
    ('usr-provider-cleaning',   0.00, 'GHS', 0, NOW(), NOW()),
    ('usr-provider-techrepair', 0.00, 'GHS', 0, NOW(), NOW());

-- ── 5. Provider category assignments ─────────────────────────────────────────
-- Category IDs are UUID-generated by V21, so we look them up by name.

INSERT INTO provider_categories (provider_id, category_id, status)
SELECT 'usr-provider-cleaning', id, 'VERIFIED'
FROM service_categories
WHERE name = 'Room Cleaning'
LIMIT 1;

INSERT INTO provider_categories (provider_id, category_id, status)
SELECT 'usr-provider-techrepair', id, 'VERIFIED'
FROM service_categories
WHERE name = 'Tech Repair'
LIMIT 1;
