-- V30__fix_admin_password_hash.sql
-- Fixes the admin password hash which was truncated in V29.
-- Password: admin123
-- Verified hash generated by BCryptPasswordEncoder: $2a$10$YDC7.tJi9wFF.REBnExtu.Sp9kuYC7Fg3L/YOqgdyXvPIJy5ZqVBa

UPDATE users 
SET password_hash = '$2a$10$YDC7.tJi9wFF.REBnExtu.Sp9kuYC7Fg3L/YOqgdyXvPIJy5ZqVBa'
WHERE id = 'usr-admin';
