package com.knust.campusserv.support.repository;

import com.knust.campusserv.support.model.Review;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

@Repository
public interface ReviewRepository extends JpaRepository<Review, String> {
    Page<Review> findByRevieweeIdOrderByCreatedAtDesc(String revieweeId, Pageable pageable);
    
    List<Review> findByJobId(String jobId);
    
    java.util.Optional<Review> findByJobIdAndDirection(String jobId, Review.ReviewDirection direction);

    @Query("SELECT r FROM Review r WHERE " +
           "(:minRating IS NULL OR r.rating >= :minRating) AND " +
           "(:maxRating IS NULL OR r.rating <= :maxRating) AND " +
           "(:isAutoGenerated IS NULL OR r.isAutoGenerated = :isAutoGenerated)")
    Page<Review> findAllWithFilters(@Param("minRating") Integer minRating,
                                    @Param("maxRating") Integer maxRating,
                                    @Param("isAutoGenerated") Boolean isAutoGenerated,
                                    Pageable pageable);
}
